/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.sfc.sf2.layout.gui;

import com.sfc.sf2.core.actions.ActionManager;
import com.sfc.sf2.core.actions.NonCombinableAction;
import com.sfc.sf2.core.gui.AbstractMainEditor;
import com.sfc.sf2.core.gui.controls.Console;
import com.sfc.sf2.core.settings.SettingsManager;
import com.sfc.sf2.core.settings.ViewSettings;
import com.sfc.sf2.layout.SpecialScreenLayoutManager;
import com.sfc.sf2.helpers.PathHelpers;
import com.sfc.sf2.layout.SpecialScreenLayout;
import java.io.File;
import java.nio.file.Path;
import java.util.logging.Level;
import javax.swing.JFileChooser;

/**
 *
 * @author wiz
 */
public class TilesetLayoutMainEditor extends AbstractMainEditor {
    
    private final ViewSettings settings = new ViewSettings();
    private final SpecialScreenLayoutManager SpecialScreenLayoutManager = new SpecialScreenLayoutManager();
    
    public TilesetLayoutMainEditor() {
        super();
        SettingsManager.registerSettingsStore("view", settings);
        initComponents();
        initCore(console1);
    }
    
    @Override
    protected void initEditor() {
        super.initEditor();
        
        accordionPanel1.setVisible(false);
        viewPanel1.setLayoutPanel(tilesetLayoutPanel, settings);
    }
    
    @Override
    protected void onDataLoaded() {
        super.onDataLoaded();
        ActionManager.setAndExecuteAction(new NonCombinableAction<SpecialScreenLayout>(this, "Layout Imported", this::actionLayoutLoaded, SpecialScreenLayoutManager.getLayout(), tilesetLayoutPanel.getLayoutTileset()));
    }
    
    private void actionLayoutLoaded(SpecialScreenLayout tileset) {
        tilesetLayoutPanel.setLayoutTileset(tileset);
        if (tileset != null) {
            viewPanel1.getItemsPerRowSpinner().setValue(tileset.getTilesPerRow());
            tilesetLayoutPanel.setItemsPerRow(tileset.getTilesPerRow());
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFileChooser1 = new javax.swing.JFileChooser();
        jFileChooser2 = new javax.swing.JFileChooser();
        jPanel13 = new javax.swing.JPanel();
        jSplitPane1 = new javax.swing.JSplitPane();
        jPanel15 = new javax.swing.JPanel();
        jSplitPane2 = new javax.swing.JSplitPane();
        jPanel8 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel18 = new javax.swing.JPanel();
        jButtonLayoutImport = new javax.swing.JButton();
        fileButtonImportTileset = new com.sfc.sf2.core.gui.controls.FileButton();
        accordionPanel1 = new com.sfc.sf2.core.gui.controls.AccordionPanel();
        fileButtonImportBaseTileset = new com.sfc.sf2.core.gui.controls.FileButton();
        fileButtonImportPalette = new com.sfc.sf2.core.gui.controls.FileButton();
        fileButtonImportLayout = new com.sfc.sf2.core.gui.controls.FileButton();
        jPanel9 = new javax.swing.JPanel();
        jButtonImportImage = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        fileButtonImportImage = new com.sfc.sf2.core.gui.controls.FileButton();
        infoButton5 = new com.sfc.sf2.core.gui.controls.InfoButton();
        jPanel5 = new javax.swing.JPanel();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel19 = new javax.swing.JPanel();
        fileButtonExportTileset = new com.sfc.sf2.core.gui.controls.FileButton();
        fileButtonExportPalette = new com.sfc.sf2.core.gui.controls.FileButton();
        fileButtonExportLayout = new com.sfc.sf2.core.gui.controls.FileButton();
        jButtonLayoutExportPalette = new javax.swing.JButton();
        jButtonLayoutExportTileset = new javax.swing.JButton();
        jButtonLayoutExportLayout = new javax.swing.JButton();
        jButtonLayoutExportAll = new javax.swing.JButton();
        jPanel14 = new javax.swing.JPanel();
        jButtonExportImage = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        fileButtonExportImage = new com.sfc.sf2.core.gui.controls.FileButton();
        infoButton6 = new com.sfc.sf2.core.gui.controls.InfoButton();
        jPanel10 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tilesetLayoutPanel = new com.sfc.sf2.layout.gui.LayoutTilesetLayoutPanel();
        viewPanel1 = new com.sfc.sf2.core.gui.controls.ViewPanel();
        console1 = new com.sfc.sf2.core.gui.controls.Console();

        jFileChooser2.setFileSelectionMode(javax.swing.JFileChooser.DIRECTORIES_ONLY);

        setTitle("SF2SpecialScreensManager");
        setPreferredSize(new java.awt.Dimension(1000, 750));

        jSplitPane1.setDividerLocation(600);
        jSplitPane1.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);
        jSplitPane1.setOneTouchExpandable(true);

        jSplitPane2.setDividerLocation(450);
        jSplitPane2.setOneTouchExpandable(true);

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Import from :"));
        jPanel3.setPreferredSize(new java.awt.Dimension(590, 135));

        jButtonLayoutImport.setText("Import");
        jButtonLayoutImport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLayoutImportActionPerformed(evt);
            }
        });

        fileButtonImportTileset.setFileFormatFilter(com.sfc.sf2.core.io.FileFormat.BIN);
        fileButtonImportTileset.setFilePath("./titlescreen/titlescreentiles.bin");
        fileButtonImportTileset.setInfoMessage("");
        fileButtonImportTileset.setLabelText("Tileset file :");
        fileButtonImportTileset.setName("Import Palette"); // NOI18N

        accordionPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Base Tileset"));

        fileButtonImportBaseTileset.setFileFormatFilter(com.sfc.sf2.core.io.FileFormat.BIN);
        fileButtonImportBaseTileset.setFilePath("../tech/basetiles.bin");
        fileButtonImportBaseTileset.setInfoMessage("");
        fileButtonImportBaseTileset.setLabelText("Base tileset :");
        fileButtonImportBaseTileset.setName("Import Palette"); // NOI18N

        javax.swing.GroupLayout accordionPanel1Layout = new javax.swing.GroupLayout(accordionPanel1);
        accordionPanel1.setLayout(accordionPanel1Layout);
        accordionPanel1Layout.setHorizontalGroup(
            accordionPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(accordionPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(fileButtonImportBaseTileset, javax.swing.GroupLayout.DEFAULT_SIZE, 406, Short.MAX_VALUE)
                .addContainerGap())
        );
        accordionPanel1Layout.setVerticalGroup(
            accordionPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(accordionPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(fileButtonImportBaseTileset, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        fileButtonImportPalette.setFileFormatFilter(com.sfc.sf2.core.io.FileFormat.BIN);
        fileButtonImportPalette.setFilePath("./titlescreen/titlescreenpalettes.bin");
        fileButtonImportPalette.setInfoMessage("");
        fileButtonImportPalette.setLabelText("Palette file :");
        fileButtonImportPalette.setName("Import Palette"); // NOI18N

        fileButtonImportLayout.setFileFormatFilter(com.sfc.sf2.core.io.FileFormat.BIN);
        fileButtonImportLayout.setFilePath("./titlescreen/titlescreenlayoutA.bin");
        fileButtonImportLayout.setInfoMessage("");
        fileButtonImportLayout.setLabelText("Layout file :");
        fileButtonImportLayout.setName("Import Palette"); // NOI18N

        javax.swing.GroupLayout jPanel18Layout = new javax.swing.GroupLayout(jPanel18);
        jPanel18.setLayout(jPanel18Layout);
        jPanel18Layout.setHorizontalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel18Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel18Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButtonLayoutImport))
                    .addComponent(fileButtonImportTileset, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(accordionPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(fileButtonImportPalette, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(fileButtonImportLayout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel18Layout.setVerticalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel18Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(accordionPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(fileButtonImportPalette, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fileButtonImportTileset, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fileButtonImportLayout, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonLayoutImport)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Layout Disassembly", jPanel18);

        jButtonImportImage.setText("Import");
        jButtonImportImage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonImportImageActionPerformed(evt);
            }
        });

        jLabel3.setText("<html>Import an image file.</html>");

        fileButtonImportImage.setFileFormatFilter(com.sfc.sf2.core.io.FileFormat.ANY_IMAGE);
        fileButtonImportImage.setFilePath("./export/specialscreen.png");
        fileButtonImportImage.setInfoMessage("");
        fileButtonImportImage.setLabelText("Image file :");
        fileButtonImportImage.setName("Import Image"); // NOI18N

        infoButton5.setMessageText("<html>Supported image formats: PNG or GIF.<br><br>Color format should be 4BPP / 16 indexed colors. Images of 8BPP / 256 indexed colors will be converted to 4 BPP / 16 (some colors may be lost).<br>Colors will be convered to CRAM format (the color format used by the SEGA Genesis).<br>Color index 0 is treated as transparent.</html>");
        infoButton5.setText("");

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButtonImportImage))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(infoButton5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(fileButtonImportImage, javax.swing.GroupLayout.DEFAULT_SIZE, 428, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(infoButton5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fileButtonImportImage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonImportImage)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Image", jPanel9);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 244, Short.MAX_VALUE)
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Export to :"));
        jPanel5.setPreferredSize(new java.awt.Dimension(32, 135));

        fileButtonExportTileset.setFileFormatFilter(com.sfc.sf2.core.io.FileFormat.BIN);
        fileButtonExportTileset.setFilePath("./titlescreen/titlescreentiles.bin");
        fileButtonExportTileset.setInfoMessage("");
        fileButtonExportTileset.setLabelText("Tileset file :");
        fileButtonExportTileset.setName("Import Palette"); // NOI18N

        fileButtonExportPalette.setFileFormatFilter(com.sfc.sf2.core.io.FileFormat.BIN);
        fileButtonExportPalette.setFilePath("./titlescreen/titlescreenpalettes.bin");
        fileButtonExportPalette.setInfoMessage("");
        fileButtonExportPalette.setLabelText("Palette file :");
        fileButtonExportPalette.setName("Import Palette"); // NOI18N

        fileButtonExportLayout.setFileFormatFilter(com.sfc.sf2.core.io.FileFormat.BIN);
        fileButtonExportLayout.setFilePath("./titlescreen/titlescreenlayoutA.bin");
        fileButtonExportLayout.setInfoMessage("");
        fileButtonExportLayout.setLabelText("Layout file :");
        fileButtonExportLayout.setName("Import Palette"); // NOI18N

        jButtonLayoutExportPalette.setText("Export Palette");
        jButtonLayoutExportPalette.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLayoutExportPaletteActionPerformed(evt);
            }
        });

        jButtonLayoutExportTileset.setText("Export Tilest");
        jButtonLayoutExportTileset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLayoutExportTilesetActionPerformed(evt);
            }
        });

        jButtonLayoutExportLayout.setText("Export Layout");
        jButtonLayoutExportLayout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLayoutExportLayoutActionPerformed(evt);
            }
        });

        jButtonLayoutExportAll.setText("Export All");
        jButtonLayoutExportAll.setToolTipText("");
        jButtonLayoutExportAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLayoutExportAllActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel19Layout = new javax.swing.GroupLayout(jPanel19);
        jPanel19.setLayout(jPanel19Layout);
        jPanel19Layout.setHorizontalGroup(
            jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel19Layout.createSequentialGroup()
                .addGroup(jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel19Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonLayoutExportPalette, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButtonLayoutExportTileset, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButtonLayoutExportLayout, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(jPanel19Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(fileButtonExportTileset, javax.swing.GroupLayout.DEFAULT_SIZE, 422, Short.MAX_VALUE)
                            .addComponent(fileButtonExportPalette, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(fileButtonExportLayout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel19Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButtonLayoutExportAll, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel19Layout.setVerticalGroup(
            jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel19Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(fileButtonExportPalette, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonLayoutExportPalette)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(fileButtonExportTileset, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonLayoutExportTileset)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(fileButtonExportLayout, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonLayoutExportLayout)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonLayoutExportAll)
                .addContainerGap())
        );

        jTabbedPane2.addTab("Layout Disassembly", jPanel19);

        jButtonExportImage.setText("Export");
        jButtonExportImage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExportImageActionPerformed(evt);
            }
        });

        jLabel9.setText("<html>Export the graphic as image.</html>");

        fileButtonExportImage.setFileFormatFilter(com.sfc.sf2.core.io.FileFormat.ANY_IMAGE);
        fileButtonExportImage.setFilePath("./export/specialscreen.png");
        fileButtonExportImage.setInfoMessage("");
        fileButtonExportImage.setLabelText("Image file :");
        fileButtonExportImage.setName("Export Image"); // NOI18N

        infoButton6.setMessageText("<html>Supported image formats: PNG or GIF.<br><br>Color format should be 4BPP / 16 indexed colors. Images of 8BPP / 256 indexed colors will be converted to 4 BPP / 16 (some colors may be lost).<br>Colors will be convered to CRAM format (the color format used by the SEGA Genesis).<br>Color index 0 is treated as transparent.</html>");
        infoButton6.setText("");

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel14Layout.createSequentialGroup()
                        .addGap(0, 350, Short.MAX_VALUE)
                        .addComponent(jButtonExportImage))
                    .addComponent(fileButtonExportImage, javax.swing.GroupLayout.DEFAULT_SIZE, 422, Short.MAX_VALUE)
                    .addGroup(jPanel14Layout.createSequentialGroup()
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(infoButton6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(infoButton6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fileButtonExportImage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonExportImage)
                .addContainerGap())
        );

        jTabbedPane2.addTab("Image", jPanel14);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane2)
        );

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 450, Short.MAX_VALUE)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, 450, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jSplitPane2.setLeftComponent(jPanel8);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Tiles"));

        javax.swing.GroupLayout tilesetLayoutPanelLayout = new javax.swing.GroupLayout(tilesetLayoutPanel);
        tilesetLayoutPanel.setLayout(tilesetLayoutPanelLayout);
        tilesetLayoutPanelLayout.setHorizontalGroup(
            tilesetLayoutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 635, Short.MAX_VALUE)
        );
        tilesetLayoutPanelLayout.setVerticalGroup(
            tilesetLayoutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 518, Short.MAX_VALUE)
        );

        jScrollPane2.setViewportView(tilesetLayoutPanel);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 510, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(viewPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(viewPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jSplitPane2.setRightComponent(jPanel10);

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane2)
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane2)
        );

        jSplitPane1.setTopComponent(jPanel15);
        jSplitPane1.setRightComponent(console1);

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(1046, 808));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonExportImageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExportImageActionPerformed
        Path graphicPath = PathHelpers.getBasePath().resolve(fileButtonExportImage.getFilePath());
        if (!PathHelpers.createPathIfRequred(graphicPath)) return;
        try {
            SpecialScreenLayout layout = tilesetLayoutPanel.getLayoutTileset();
            layout.setTilesPerRow((int)viewPanel1.getItemsPerRowSpinner().getValue());
            SpecialScreenLayoutManager.exportImage(graphicPath, layout);
        } catch (Exception ex) {
            Console.logger().log(Level.SEVERE, null, ex);
            Console.logger().severe("ERROR Layout image could not be exported to : " + graphicPath);
        }
    }//GEN-LAST:event_jButtonExportImageActionPerformed

    private void jButtonImportImageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonImportImageActionPerformed
        Path graphicPath = PathHelpers.getBasePath().resolve(fileButtonImportImage.getFilePath());
        try {
            SpecialScreenLayoutManager.importImage(graphicPath, true);
        } catch (Exception ex) {
            SpecialScreenLayoutManager.clearData();
            Console.logger().log(Level.SEVERE, null, ex);
            Console.logger().severe("ERROR Graphic image could not be imported from : " + graphicPath);
        }
        onDataLoaded();
    }//GEN-LAST:event_jButtonImportImageActionPerformed

    private void jButtonLayoutImportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLayoutImportActionPerformed
        Path baseTilesetPath = PathHelpers.getBasePath().resolve(fileButtonImportBaseTileset.getFilePath());
        Path palettePath = PathHelpers.getBasePath().resolve(fileButtonImportPalette.getFilePath());
        Path tilesetPath = PathHelpers.getBasePath().resolve(fileButtonImportTileset.getFilePath());
        Path layoutPath = PathHelpers.getBasePath().resolve(fileButtonImportLayout.getFilePath());
        try {
            SpecialScreenLayoutManager.importDisassembly(baseTilesetPath, palettePath, tilesetPath, layoutPath);
        } catch (Exception ex) {
            SpecialScreenLayoutManager.clearData();
            Console.logger().log(Level.SEVERE, null, ex);
            Console.logger().severe("ERROR Tileset/Layout could not be imported");
        }
        onDataLoaded();
    }//GEN-LAST:event_jButtonLayoutImportActionPerformed

    private void jButtonLayoutExportPaletteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLayoutExportPaletteActionPerformed
        Path palettePath = PathHelpers.getBasePath().resolve(fileButtonExportPalette.getFilePath());
        try {
            SpecialScreenLayoutManager.exportPalette(tilesetLayoutPanel.getLayoutTileset(), palettePath);
        } catch (Exception ex) {
            SpecialScreenLayoutManager.clearData();
            Console.logger().log(Level.SEVERE, null, ex);
            Console.logger().severe("ERROR Layout palette could not be imported");
        }
    }//GEN-LAST:event_jButtonLayoutExportPaletteActionPerformed

    private void jButtonLayoutExportTilesetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLayoutExportTilesetActionPerformed
        Path tilesetPath = PathHelpers.getBasePath().resolve(fileButtonExportTileset.getFilePath());
        try {
            SpecialScreenLayoutManager.exportPalette(tilesetLayoutPanel.getLayoutTileset(), tilesetPath);
        } catch (Exception ex) {
            SpecialScreenLayoutManager.clearData();
            Console.logger().log(Level.SEVERE, null, ex);
            Console.logger().severe("ERROR Layout tileset could not be imported");
        }
    }//GEN-LAST:event_jButtonLayoutExportTilesetActionPerformed

    private void jButtonLayoutExportLayoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLayoutExportLayoutActionPerformed
        Path layoutPath = PathHelpers.getBasePath().resolve(fileButtonExportLayout.getFilePath());
        try {
            SpecialScreenLayoutManager.exportPalette(tilesetLayoutPanel.getLayoutTileset(), layoutPath);
        } catch (Exception ex) {
            SpecialScreenLayoutManager.clearData();
            Console.logger().log(Level.SEVERE, null, ex);
            Console.logger().severe("ERROR Layout could not be imported");
        }
    }//GEN-LAST:event_jButtonLayoutExportLayoutActionPerformed

    private void jButtonLayoutExportAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLayoutExportAllActionPerformed
        jButtonLayoutExportPaletteActionPerformed(evt);
        jButtonLayoutExportTilesetActionPerformed(evt);
        jButtonLayoutExportLayoutActionPerformed(evt);
    }//GEN-LAST:event_jButtonLayoutExportAllActionPerformed

    /**
     * To create a new Main Editor, copy the below code
     * Don't forget to change the new main class (below)
     */
    public static void main(String args[]) {
        AbstractMainEditor.programSetup();
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TilesetLayoutMainEditor().setVisible(true);  // <------ Change this class to new Main Editor class
            }
        });
    }
    /**
     * To create a new Main Editor, copy the above code
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.sfc.sf2.core.gui.controls.AccordionPanel accordionPanel1;
    private com.sfc.sf2.core.gui.controls.Console console1;
    private com.sfc.sf2.core.gui.controls.FileButton fileButtonExportImage;
    private com.sfc.sf2.core.gui.controls.FileButton fileButtonExportLayout;
    private com.sfc.sf2.core.gui.controls.FileButton fileButtonExportPalette;
    private com.sfc.sf2.core.gui.controls.FileButton fileButtonExportTileset;
    private com.sfc.sf2.core.gui.controls.FileButton fileButtonImportBaseTileset;
    private com.sfc.sf2.core.gui.controls.FileButton fileButtonImportImage;
    private com.sfc.sf2.core.gui.controls.FileButton fileButtonImportLayout;
    private com.sfc.sf2.core.gui.controls.FileButton fileButtonImportPalette;
    private com.sfc.sf2.core.gui.controls.FileButton fileButtonImportTileset;
    private com.sfc.sf2.core.gui.controls.InfoButton infoButton5;
    private com.sfc.sf2.core.gui.controls.InfoButton infoButton6;
    private javax.swing.JButton jButtonExportImage;
    private javax.swing.JButton jButtonImportImage;
    private javax.swing.JButton jButtonLayoutExportAll;
    private javax.swing.JButton jButtonLayoutExportLayout;
    private javax.swing.JButton jButtonLayoutExportPalette;
    private javax.swing.JButton jButtonLayoutExportTileset;
    private javax.swing.JButton jButtonLayoutImport;
    private javax.swing.JFileChooser jFileChooser1;
    private javax.swing.JFileChooser jFileChooser2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JSplitPane jSplitPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private com.sfc.sf2.layout.gui.LayoutTilesetLayoutPanel tilesetLayoutPanel;
    private com.sfc.sf2.core.gui.controls.ViewPanel viewPanel1;
    // End of variables declaration//GEN-END:variables

}
