name: auto tag builds

on:
  push:
    branches:
      - test/versioning
    paths:
      - '**/version.properties'

jobs:
  tag-version:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository (full history)
      uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Required so git diff can see commit history

    - name: Detect changed version.properties files
      id: detect_changes
      run: |
        changed_files=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} -- '**/version.properties')

        if [ -z "$changed_files" ]; then
          echo "No version.properties files changed."
          echo "should_run=false" >> $GITHUB_OUTPUT
        else
          echo "Found changes in:"
          echo "$changed_files"
          echo "should_run=true" >> $GITHUB_OUTPUT
          echo "changed_files<<EOF" >> $GITHUB_OUTPUT
          echo "$changed_files" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT
        fi

    - name: Tag version updates
      if: steps.detect_changes.outputs.should_run == 'true'
      run: |
        echo "${{ steps.detect_changes.outputs.changed_files }}" | while read file_path; do
          if [ -f "$file_path" ]; then
            folder_name=$(basename "$(dirname "$file_path")")
            version=$(grep '^version:' "$file_path" | cut -d':' -f2 | xargs)
            tag_name="${folder_name}_${version}"
            echo "Tagging $tag_name from $file_path"
            git config user.name 'GitHub Auto Merge Action'
            git config user.email 'actions@github.com'

            if git rev-parse "$tag_name" >/dev/null 2>&1; then
              echo "Tag $tag_name already exists. Skipping."
            else
              git tag "$tag_name"
              git push origin "$tag_name"
            fi
          fi
        done
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
